set(CMAKE_SYSTEM_NAME Windows)
set(WOS_WINDOWS_ARCH x86_64 CACHE STRING "Windows target: x86_64 or i686")
set_property(CACHE WOS_WINDOWS_ARCH PROPERTY STRINGS x86_64 i686)
if(NOT WOS_WINDOWS_ARCH MATCHES "^(x86_64|i686)$")
    message(FATAL_ERROR "WOS_WINDOWS_ARCH must be x86_64 or i686")
endif()
set(CMAKE_SYSTEM_PROCESSOR "${WOS_WINDOWS_ARCH}")
set(WOS_TOOLCHAIN_CACHE "$ENV{HOME}/.cache/wos-toolchains" CACHE PATH "Toolchain download cache")
set(_llvm "${WOS_TOOLCHAIN_CACHE}/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64")
set(_triple "${WOS_WINDOWS_ARCH}-w64-mingw32")
set(_sdl "${WOS_TOOLCHAIN_CACHE}/SDL2-2.32.10/${_triple}")
if(NOT EXISTS "${_llvm}/bin/${_triple}-clang" OR NOT EXISTS "${_sdl}/bin/SDL2.dll")
    execute_process(COMMAND sh "${CMAKE_CURRENT_LIST_DIR}/../tools/fetch_toolchains.sh" RESULT_VARIABLE _fetch)
endif()
if(NOT EXISTS "${_llvm}/bin/${_triple}-clang" OR NOT EXISTS "${_sdl}/bin/SDL2.dll")
    message(FATAL_ERROR "Windows prerequisites missing and tools/fetch_toolchains.sh failed (${_fetch}).")
endif()
set(CMAKE_C_COMPILER "${_llvm}/bin/${_triple}-clang")
set(CMAKE_RC_COMPILER "${_llvm}/bin/${_triple}-windres")
set(CMAKE_FIND_ROOT_PATH "${_llvm}/${_triple}" "${_sdl}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(SDL2_DIR "${_sdl}/lib/cmake/SDL2" CACHE PATH "Windows SDL2 CMake package")
set(WOS_SDL2_DLL "${_sdl}/bin/SDL2.dll" CACHE FILEPATH "Windows SDL2 runtime")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES WOS_WINDOWS_ARCH WOS_TOOLCHAIN_CACHE)
